// Generated by LiveScript 1.3.1
angular.module("parliva").controller('ProfileController', ['$scope', '$interval', '$rootScope', '$meteor', 'plCategories'].concat(function($scope, $interval, $rootScope, $meteor, plCategories){
  $scope.categories = plCategories.get();
  console.log($scope.categories);
  $scope.save = function(){
    if ($scope.portrait) {
      $rootScope.currentUser.profile.portraitURL = $scope.portrait.url();
    }
    return Meteor.users.update($rootScope.currentUser._id, {
      $set: {
        profile: $rootScope.currentUser.profile
      }
    }, function(err, result){
      if (err) {
        return sweetAlert("Oops...", "Something went wrong!", "error");
      } else {
        return swal("Profile saved!", "You successfully saved your profile!", "success");
      }
    });
  };
  Tracker.autorun(function(comp){
    var user;
    user = Meteor.user();
    if (user && user.profile && user.profile.portraitId) {
      $scope.portrait = Portraits.findOne(user.profile.portraitId);
    }
    if (!comp.firstRun) {
      return $scope.$apply();
    }
  });
  return $scope.changePortrait = function(files){
    if (files.length > 0) {
      return Portraits.insert(files[0], function(err, fileObj){
        if (!err) {
          return Meteor.users.update($rootScope.currentUser._id, {
            $set: {
              "profile.portraitId": fileObj._id
            }
          });
        }
      });
    }
  };
}));