// Generated by LiveScript 1.3.1
angular.module('parliva').controller('MessagesController', ['$scope', '$meteor'].concat(function($scope, $meteor){
  $scope.messages = $meteor.collection(Messages, false).subscribe('messages');
  return $scope.latestMessages = function(messages){
    var userId, ref$, msgs, results$ = [];
    for (userId in ref$ = _.groupBy(messages, fn$)) {
      msgs = ref$[userId];
      results$.push(_.max(msgs, fn1$));
    }
    return results$;
    function fn$(m){
      return m.senderId;
    }
    function fn1$(m){
      return m.date;
    }
  };
}));