// Generated by LiveScript 1.3.1
angular.module('parliva').controller('ChatController', ['$scope', '$meteor', '$stateParams'].concat(function($scope, $meteor, $stateParams){
  $scope.aux = {
    callStatus: "none",
    kandyStatus: "none"
  };
  $scope.newMessage = {};
  $scope.messages = $meteor.collection(Messages, false).subscribe('chat_messages', $stateParams.userId);
  $scope.partners = $meteor.collection(Meteor.users, false).subscribe('chat_partners', $stateParams.userId);
  $scope.partner = $meteor.object(Meteor.users, $stateParams.userId);
  $scope.call = function(){
    return KandyAux.makeCall($scope.partner.kandyData.full_user_id);
  };
  $scope.endCall = function(){
    return KandyAux.endCall();
  };
  $scope.isMe = function(message){
    return $scope.currentUser && message.senderId === $scope.currentUser._id;
  };
  $scope.sendMessage = function(){
    $scope.messages.save({
      roomUserIds: [$scope.currentUser._id, $scope.partner._id],
      text: $scope.newMessage.text,
      userName: $scope.currentUser.username,
      senderId: $scope.currentUser._id,
      portraitURL: $scope.currentUser.profile && $scope.currentUser.profile.portraitURL
    });
    return $scope.newMessage = {};
  };
  setTimeout(function(){
    var chatContainer;
    chatContainer = $('.panel-body');
    return chatContainer.scrollTop(chatContainer.prop("scrollHeight"));
  }, 1000);
  Meteor.call('pay', $stateParams.userId, function(error, result){
    console.log(error, result);
    $scope.paypalUrl = result;
    return $scope.$apply();
  });
  return KandyAux.init($scope);
}));