// Generated by LiveScript 1.3.1
var usernameRegex, validateUserFunc;
usernameRegex = new RegExp("^[a-zA-Z0-9]+$");
validateUserFunc = function(user){
  if (usernameRegex.test(user.username)) {
    return true;
  }
  throw new Meteor.Error(403, "passwordRegexValidation");
};
Accounts.validateNewUser(validateUserFunc);