// Generated by LiveScript 1.3.1
Messages.allow({
  insert: function(userId, doc){
    doc.senderId = userId;
    doc.date = new Date();
    return true;
  },
  update: function(){
    return false;
  },
  remove: function(){
    return false;
  }
});
Portraits.allow({
  download: function(userId, fileObj){
    return true;
  },
  insert: function(userId, doc){
    return true;
  },
  update: function(){
    return true;
  },
  remove: function(){
    return true;
  }
});