// Generated by LiveScript 1.3.1
Router.route('/paypal', function(){
  console.log("paypal!");
  console.log(this.request);
  console.log(this.response);
  return this.response.end('file download content\n');
}, {
  where: 'server'
});