// Generated by LiveScript 1.3.1
angular.module('parliva').config(['$urlRouterProvider', '$stateProvider', '$locationProvider'].concat(function($urlRouterProvider, $stateProvider, $locationProvider){
  var auth;
  $locationProvider.html5Mode(true);
  auth = ['$meteor'].concat(function($meteor){
    return $meteor.requireUser();
  });
  $stateProvider.state('entrySignIn', {
    url: '/sign-in',
    template: '<meteor-include src="entrySignIn"></meteor-include>'
  }).state('entrySignUp', {
    url: '/sign-up',
    template: '<meteor-include src="entrySignUp"></meteor-include>'
  }).state('landing', {
    url: '/',
    templateUrl: 'client/views/landing/landing.ng.html',
    controller: 'LandingController'
  }).state('dashboard', {
    url: '/dashboard',
    templateUrl: 'client/views/dashboard/dashboard.ng.html',
    controller: 'DashboardController',
    resolve: {
      currentUser: auth
    }
  }).state('profile', {
    url: '/profile',
    templateUrl: 'client/views/profile/profile.ng.html',
    controller: 'ProfileController',
    resolve: {
      currentUser: auth
    }
  }).state('messages', {
    url: '/messages',
    templateUrl: 'client/views/messages/messages.ng.html',
    controller: 'MessagesController',
    resolve: {
      currentUser: auth
    }
  }).state('chat', {
    url: '/chat/:userId',
    templateUrl: 'client/views/chat/chat.ng.html',
    controller: 'ChatController',
    resolve: {
      currentUser: auth
    }
  });
  $urlRouterProvider.otherwise('/dashboard');
}));
angular.module('parliva').run(['$rootScope', '$state'].concat(function($rootScope, $state){
  $rootScope.$on('$stateChangeError', function(event, toState, toParams, fromState, fromParams, error){
    if (error === 'AUTH_REQUIRED') {
      $state.go('entrySignIn');
    }
  });
}));