// Generated by LiveScript 1.4.0
angular.module('angularMeteor').config(['$urlRouterProvider', '$stateProvider', '$locationProvider'].concat(function($urlRouterProvider, $stateProvider, $locationProvider){
  var auth;
  $locationProvider.html5Mode(true);
  auth = ['$meteor'].concat(function($meteor){
    return $meteor.requireUser();
  });
  $stateProvider.state('entrySignIn', {
    url: '/sign-in',
    template: '<meteor-include src="entrySignIn"></meteor-include>'
  }).state('entrySignUp', {
    url: '/sign-up',
    template: '<meteor-include src="entrySignUp"></meteor-include>'
  }).state('home', {
    url: '/',
    templateUrl: 'client/views/home/home.html',
    controller: 'HomeController'
  }).state('dashboard', {
    url: '/dashboard',
    templateUrl: 'client/views/dashboard/dashboard.html',
    controller: 'DashboardController',
    resolve: {
      currentUser: auth
    }
  });
  $urlRouterProvider.otherwise('/');
}));
angular.module('angularMeteor').run(['$rootScope', '$state'].concat(function($rootScope, $state){
  $rootScope.$on('$stateChangeError', function(event, toState, toParams, fromState, fromParams, error){
    if (error === 'AUTH_REQUIRED') {
      $state.go('entrySignIn');
    }
  });
}));